### PR TITLE
53 Add change password endpoint

### LINKED ISSUE #53: Add change password endpoint
Trzeba dodać endpoint, który pozwoli zalogowanemu użytkownikowi zmienić swoje hasło.  
Użytkownik musi podać obecne hasło oraz nowe. Jeśli obecne hasło jest poprawne, system ustawia nowe.

---

#### DTO

1. Utworzyć `ChangePasswordRequestDto` (nie może być jako record!)

#### Endpoint API (`AuthController`)
 
2. Dodać `POST /auth/change-password` (metoda `ChangePassword`, która przyjmuje `[FromBody] ChangePasswordRequestDto request` i zwraca `AuthResponseDto` z nowym JWT.

#### Serwis `IAuthService`

3. Rozszerzyć interfejs o:
- `ChangePasswordAsync(Guid userId, ChangePasswordRequestDto request)`

#### `AuthService`

4. Implementacja:
- Pobrać użytkownika z bazy.
- Sprawdzić, czy `CurrentPassword` pasuje (użyć `IPasswordHasher`).
- Jeśli nie – rzucić wyjątkiem (np. `InvalidPasswordException` z kodem `INVALID_PASSWORD`, `400`).
- Jeśli tak, zapisać zahashowane hasło do bazy.

#### Obsługa błędów

5. Dodać odpowiedni `ErrorCode` do np. `AuthErrorCode`: `INVALID_PASSWORD`

### PR DESCRIPTION
**Pull request by Pucha10**
Closed #53 
Added ChangePasswordRequestDto
Added ChangePasswordAsync in IAuthService
Implemented ChangePasswordAsync in AuthService
Added EndPoint in AuthController
Implemented UpdateAsync in UserRepository

### CODE REVIEW

File: Application/DTOs/Auth/ChangePasswordRequestDto.cs [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+/// <summary>
+/// Represents the data transfer object used for user registration requests.
+/// </summary>
+public class ChangePasswordRequestDto
+{
+    /// <summary>
+    /// Gets the current email address of the user.
+    /// </summary>
+    [Required]
+    public required string CurrentPassword { get; init; }
```
Comment (Rivixer) [inline Application/DTOs/Auth/ChangePasswordRequestDto.cs:14]:
```suggestion
    /// <summary>
    /// Gets the current password of the user.
    /// </summary>
    [Required]
    public required string CurrentPassword { get; init; }
```

File: Application/DTOs/Auth/ChangePasswordRequestDto.cs [hunk 2]
```diff
@@ -0,0 +1,21 @@
+﻿using System.ComponentModel.DataAnnotations;
+
+namespace Application.DTOs.Auth;
+
+/// <summary>
+/// Represents the data transfer object used for user registration requests.
+/// </summary>
+public class ChangePasswordRequestDto
```
Comment (Rivixer) [inline Application/DTOs/Auth/ChangePasswordRequestDto.cs:8]:
```suggestion
/// <summary>
/// Represents the data transfer object used for password change requests.
/// </summary>
public class ChangePasswordRequestDto
```

File: API/Models/Errors/Auth/AuthErrorCode.cs [hunk 3]
```diff
@@ -19,4 +19,9 @@ public enum AuthErrorCode
     /// The token has expired and is no longer valid.
     /// </summary>
     EXPIRED_TOKEN,
+
+    /// <summary>
+    /// The user is not authorized to access the requested resource.
+    /// </summary>
+    INVALID_PASSWORD,
```
Comment (Rivixer) [inline API/Models/Errors/Auth/AuthErrorCode.cs:26]: W issue wspomniałem o `INVALID_PASSWORD`, jednak dopisanie CURRENT da więcej kontekstu.
```suggestion
    /// <summary>
    /// The provided current password is incorrect.
    /// </summary>
    /// <remarks>
    /// Used when the user attempts to change their password and the provided current password
    /// does not match the stored password.
    /// </remarks>
    INVALID_CURRENT_PASSWORD,
```

File: API/Controllers/AuthController.cs [hunk 4]
```diff
@@ -87,6 +87,29 @@ public async Task<ActionResult<AuthResponseDto>> Me()
         return this.Ok(result);
     }
 
+    /// <summary>
+    /// Changes the password of the currently authenticated user.
+    /// </summary>
+    /// <param name="request">The change-password request containing email, nickname, and password.</param>
```
Comment (Rivixer) [inline API/Controllers/AuthController.cs:93]:
```suggestion
    /// <summary>
    /// Changes the password of the currently authenticated user.
    /// </summary>
    /// <param name="request">The change-password request containing current and new password.</param>
```

File: Domain/Interfaces/IUserRepository.cs [hunk 5]
```diff
@@ -27,4 +27,11 @@ public interface IUserRepository
     /// <param name="user">The user to add.</param>
     /// <returns>A task representing the asynchronous operation.</returns>
     Task AddAsync(User user);
+
+    /// <summary>
+    /// Updates an existing user in the database.
+    /// </summary>
+    /// <param name="user">The user to add.</param>
```
Comment (Rivixer) [inline Domain/Interfaces/IUserRepository.cs:34]:
```suggestion
    /// <summary>
    /// Updates an existing user in the database.
    /// </summary>
    /// <param name="user">The user to update.</param>
```

**Review by Rivixer — CHANGES_REQUESTED** [review]

File: API/Controllers/AuthController.cs [hunk 6]
```diff
@@ -87,6 +87,29 @@ public async Task<ActionResult<AuthResponseDto>> Me()
...
+    /// Changes the password of the currently authenticated user.
+    /// </summary>
+    /// <param name="request">The change-password request containing current and new password.</param>
+    /// <returns>The authenticated user's data and token.</returns>
+    /// <response code="200">The user password has been changed successfully.</response>
+    /// <response code="400">The request payload is invalid.</response>
+    [HttpPost("change-password")]
+    [ProducesResponseType(typeof(AuthResponseDto), StatusCodes.Status200OK)]
+    [ProducesResponseType(typeof(ErrorResponse<AuthErrorCode>), StatusCodes.Status400BadRequest)]
+    [ProducesResponseType(typeof(ErrorResponse<AuthErrorCode>), StatusCodes.Status404NotFound)]
```
Comment (Rivixer) [inline API/Controllers/AuthController.cs:100]: Brak opisu 404 w `<response>`. AuthErrorCode nie ma wartości `USER_NOT_FOUND`.

**Review by Rivixer — APPROVED** [review]
